apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
spec:
  host: guestbook.apps.s9cqd.sandbox1011.opentlc.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: guestbook
    weight: 100
